#pragma once

/**
 * @file qbuem/transport/quiche_transport.hpp
 * @brief QUIC/HTTP3 transport layer — quiche FFI ITransport reference implementation guide.
 * @ingroup qbuem_transport
 *
 * ## Overview
 *
 * This file is a **reference guide** describing how to implement the QUIC/HTTP3
 * transport layer directly in a service using the `ITransport` interface.
 *
 * qbuem-stack does not link quiche/ngtcp2 directly, following the zero-dependency
 * principle. Services that need QUIC functionality should inject their own
 * implementation as `ITransport` following the guide below.
 *
 * ## Dependency options
 *
 * | Library | Characteristics | Recommended for |
 * |---------|-----------------|-----------------|
 * | **quiche** (Cloudflare) | Rust-based, stable, HTTP/3 built-in | Production use |
 * | **ngtcp2** | C-based, low-level control | Custom protocols |
 * | **msquic** (Microsoft) | Windows/Linux, high performance | Microsoft stack integration |
 * | **mvfst** (Meta) | C++, folly-based | Meta infrastructure stack |
 *
 * ## Implementation example (quiche-based)
 *
 * ```cmake
 * # CMakeLists.txt (service project)
 * find_package(qbuem-stack REQUIRED COMPONENTS transport)
 *
 * # Link the static library generated by cargo build for quiche
 * add_library(quiche_transport_impl STATIC quiche_transport.cpp)
 * target_link_libraries(quiche_transport_impl
 *     PUBLIC  qbuem-stack::transport
 *     PRIVATE quiche  # cargo build --release → target/release/libquiche.a
 * )
 * ```
 *
 * ```cpp
 * // quiche_transport.hpp (service implementation)
 * #include <qbuem/transport/quiche_transport.hpp>  // this guide header
 *
 * class QuicheTransport : public qbuem::ITransport {
 * public:
 *     explicit QuicheTransport(quiche_conn* conn) : conn_(conn) {}
 *
 *     qbuem::Task<qbuem::Result<size_t>>
 *     read(qbuem::MutableBufferView buf) override {
 *         // Read from QUIC stream (stream ID passed via context)
 *         ssize_t n = quiche_conn_stream_recv(conn_, stream_id_,
 *             reinterpret_cast<uint8_t*>(buf.data()), buf.size(), &fin_);
 *         if (n == QUICHE_ERR_DONE) {
 *             // No data — wait for reactor wakeup (retry after UDP recv)
 *             co_await io_event_;
 *             co_return co_await read(buf); // recursive call
 *         }
 *         if (n < 0) {
 *             co_return qbuem::unexpected(
 *                 std::make_error_code(std::errc::io_error));
 *         }
 *         co_return static_cast<size_t>(n);
 *     }
 *
 *     qbuem::Task<qbuem::Result<size_t>>
 *     write(qbuem::BufferView buf) override {
 *         ssize_t n = quiche_conn_stream_send(conn_, stream_id_,
 *             reinterpret_cast<const uint8_t*>(buf.data()), buf.size(),
 *             /*fin=*/false);
 *         if (n < 0) {
 *             co_return qbuem::unexpected(
 *                 std::make_error_code(std::errc::io_error));
 *         }
 *         co_return static_cast<size_t>(n);
 *     }
 *
 *     qbuem::Task<void> close() override {
 *         quiche_conn_close(conn_, /*app=*/true, 0, nullptr, 0);
 *         co_return;
 *     }
 *
 *     [[nodiscard]] bool is_open() const noexcept override {
 *         return !quiche_conn_is_closed(conn_);
 *     }
 *
 * private:
 *     quiche_conn* conn_;
 *     uint64_t     stream_id_ = 0;
 *     bool         fin_       = false;
 *     // reactor wakeup awaiter (UDP recv completion signal)
 *     qbuem::IoEvent io_event_;
 * };
 * ```
 *
 * ## HTTP/3 request processing flow
 *
 * ```
 * UDP Socket (qbuem::UdpSocket)
 *     │
 *     │  recvfrom() → UDP datagram
 *     ▼
 * quiche_conn_recv()        ← QUIC packet processing (decryption, ACK, etc.)
 *     │
 *     │  quiche_h3_conn_poll()
 *     ▼
 * HTTP/3 event dispatch
 *     ├── H3_EVENT_HEADERS  → Router mapping → Handler invocation
 *     ├── H3_EVENT_DATA     → request body streaming
 *     └── H3_EVENT_FINISHED → request complete
 *
 * Handler response → quiche_h3_send_response()
 *     │
 *     │  quiche_conn_send() → UDP datagram
 *     ▼
 * UDP Socket.sendto()
 * ```
 *
 * ## 0-RTT (Zero Round Trip Time)
 *
 * ```cpp
 * // Server: configure 0-RTT session ticket
 * quiche_config_set_max_idle_timeout(cfg, 30000);   // 30 seconds
 * quiche_config_set_initial_max_data(cfg, 10485760); // 10 MiB
 *
 * // Client: send early data
 * quiche_conn_send_ach(conn, buf, len);  // 0-RTT QUIC packet
 * // HTTP/3 request can be sent before TLS handshake completes
 * ```
 *
 * ## Connection Migration
 *
 * QUIC maintains connections without IP address/port changes (e.g. mobile network switching).
 *
 * ```cpp
 * // Validate new path after connection migration
 * quiche_conn_probe_path(conn, new_local, local_len, new_peer, peer_len, &seq);
 * // Switch path after validation completes
 * quiche_conn_migrate(conn, new_local, local_len, new_peer, peer_len);
 * ```
 *
 * ## Multiplexing (No HOL Blocking)
 *
 * ```cpp
 * // HTTP/3 per-stream multiplexing → no Head-of-Line Blocking
 * // Connect to qbuem Pipeline:
 * qbuem::AsyncChannel<Http3Request> req_channel{256};
 *
 * // Independent Task per QUIC stream
 * for (auto stream_id : new_streams) {
 *     dispatcher.spawn(handle_h3_stream(conn, stream_id, req_channel));
 * }
 * ```
 *
 * ## Build guide (quiche)
 *
 * ```sh
 * # 1. Build quiche (requires Rust)
 * git clone --recursive https://github.com/cloudflare/quiche.git
 * cd quiche && cargo build --release --features ffi
 *
 * # 2. Build service
 * cmake -DQUICHE_DIR=/path/to/quiche/target/release ..
 * ```
 *
 * ## References
 *
 * - [quiche GitHub](https://github.com/cloudflare/quiche)
 * - [RFC 9000 — QUIC](https://www.rfc-editor.org/rfc/rfc9000)
 * - [RFC 9114 — HTTP/3](https://www.rfc-editor.org/rfc/rfc9114)
 * - [RFC 9001 — TLS 1.3 for QUIC](https://www.rfc-editor.org/rfc/rfc9001)
 * - [QUIC performance measurement (IETF)](https://datatracker.ietf.org/doc/html/rfc9312)
 *
 * @note This header is an implementation guide and does not contain actual code.
 *       Link quiche, ngtcp2, etc. directly in your service.
 */

#include <qbuem/core/transport.hpp>
#include <qbuem/net/udp_socket.hpp>

namespace qbuem {

/**
 * @brief QUIC/HTTP3 ITransport implementation template.
 *
 * Refer to this struct in your service to write an implementation that
 * wraps a QUIC library such as quiche / ngtcp2 as an `ITransport`.
 *
 * @par Minimum implementation list
 * - `read(MutableBufferView)` — read data from QUIC stream
 * - `write(BufferView)` — write data to QUIC stream
 * - `close()` — close stream / connection
 * - `is_open()` — connection active status
 *
 * @par Additional QUIC-specific implementation
 * - 0-RTT early data handling
 * - Connection migration handling
 * - ALPN negotiation ("h3" or custom protocol)
 * - DATAGRAM frames (RFC 9221, unreliable messaging)
 */
struct QuicTransportGuide {
    // This struct exists for documentation purposes only.
    // Implement ITransport by inheriting from it in your service code.
    static_assert(sizeof(QuicTransportGuide) == 0,
        "QuicTransportGuide is a documentation-only type. "
        "Implement ITransport in your service code.");
};

} // namespace qbuem
